questionnaire/forms/questionnaire_form.py
from wtforms import Form, RadioField


def likert(statements, start, end):
    class _Likert(Form):
        pass

    for statement in statements:
        setattr(
            _Likert,
            str(statement["id"]),
            RadioField(
                statement["question"],
                choices=[(value, value) for value in range(start, end + 1)],
            ),
        )

    return _Likert()

questionnaire/blueprints/authentication.py
import functools

from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from questionnaire import db

from questionnaire.forms.authentication_forms import (
    RegistrationForm,
    LoginForm,
    PasswordResetForm,
    PasswordChangeForm,
    GetUsernameForm,
)

from questionnaire.models import Student

bp = Blueprint("authentication", __name__, url_prefix="/auth")


@bp.before_app_request
def load_logged_in_user():
    student_id = session.get("student_id")

    if not student_id:
        g.student = None
    else:
        g.student = Student.query.filter_by(id=student_id).first()


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if not g.student:
            return redirect(url_for("authentication.login"))
        return view(**kwargs)

    return wrapped_view


@bp.route("/register", methods=("GET", "POST"))
def register():
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        if Student.query.filter_by(username=username).first():
            flash(
                f"Username {username} has been taken. Please try a different username.",
                "danger",
            )
        else:
            db.session.add(
                Student(
                    first_name=form.first_name.data.lower(),
                    last_name=form.last_name.data.lower(),
                    student_id_last_three_digits=form.student_id_last_three_digits.data,
                    username=username,
                    password_hash=Student.hash_password(form.password.data),
                    admin=False,
                )
            )
            db.session.commit()
            flash(
                f"Registration successful. You may log in with your username: {username}.",
                "success",
            )
            return redirect(url_for("authentication.login"))

    return render_template("login_views/register.html", form=form)


@bp.route("/login", methods=("GET", "POST"))
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        student = Student.query.filter_by(username=form.username.data).first()

        if not student or not student.check_password(form.password.data):
            flash("Incorrect password or username does not exist", "danger")

        else:
            session.clear()
            session["student_id"] = student.id
            return redirect(url_for("questionnaire.questionnaire_list"))

    return render_template("login_views/login.html", form=form)


@bp.route("/password-reset", methods=("GET", "POST"))
def password_reset():
    form = PasswordResetForm(request.form)
    if form.validate_on_submit():
        student = Student.query.filter_by(
            username=form.username.data,
            student_id_last_three_digits=form.student_id_last_three_digits.data,
        ).first()

        if not student:
            flash("No user found with username or student ID provided.", "danger")
        else:
            student.password_hash = Student.hash_password(form.password.data)
            db.session.commit()
            flash(
                "Password was changed successfully. Please login with your new password.",
                "success",
            )
            return redirect(url_for("authentication.login"))

    return render_template("login_views/password_reset.html", form=form)


@bp.route("/password-change", methods=("GET", "POST"))
@login_required
def password_change():
    form = PasswordChangeForm(request.form)
    if form.validate_on_submit():
        g.student.password_hash = Student.hash_password(form.password.data)
        db.session.commit()
        flash("Password successfully changed", "success")
        return redirect(url_for("questionnaire.questionnaire_list"))

    return render_template("login_views/password_reset.html", form=form)


@bp.route("/get-username", methods=("GET", "POST"))
def get_username():
    form = GetUsernameForm(request.form)

    if form.validate_on_submit():
        student = Student.query.filter_by(
            first_name=form.first_name.data.lower(),
            last_name=form.last_name.data.lower(),
            student_id_last_three_digits=form.student_id_last_three_digits.data,
        ).first()

        if not student:
            flash("No username found with the name and student ID provided.", "danger")
        else:
            flash(f"Your username is: {student.username}", "primary")

    return render_template("login_views/get_username.html", form=form)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index.index"))

questionnaire/blueprints/questionnaire.py
from flask import Blueprint, g, render_template, request, session
import itertools
from questionnaire import db
from questionnaire.blueprints.authentication import login_required
from questionnaire.models import Instrument, FormHeader, TutorialTopic
import random

bp = Blueprint("questionnaire", __name__)


@bp.route("/questionnaire-list")
@login_required
def questionnaire_list():
    order = ("s7_meta", "s6_cog", "s1_learn", "s4_beh", "s5_socemo", "s2_rlq")
    topics = (
        TutorialTopic.query.filter_by(code=topic_code).first()
        for topic_code in order
    )
    return render_template("questionnaire_list.html", topics=topics)


@bp.route("/questionnaire/<tutorial_topic_code>")
@login_required
def questionnaire(tutorial_topic_code):
    # Checks if topic code is valid or returns 404 if code not found
    TutorialTopic.query.filter_by(code=tutorial_topic_code).first_or_404()

    session["tutorial_topic_code"] = tutorial_topic_code

    return render_template(
        "questionnaire.html",
        title=TutorialTopic.query.filter_by(code=tutorial_topic_code)
        .first()
        .topic,
        formheaders_and_instruments=formheaders_and_instruments(
            formheaders_with(tutorial_topic_code)
        ),
    )


def formheaders_and_instruments(formheaders):
    return {
        formheader: section_by_formheader(formheader)
        for formheader in formheaders
    }


def section_by_formheader(formheader):
    instruments_of_formheader = (
        FormHeader.query.filter_by(code=formheader.code).first().instruments
    )

    if formheader.tutorial_topic_code == "s2_rlq":
        yield instrument_view_object(instruments_of_formheader)
    else:
        unique_instrument_names = set(
            map(lambda x: x.name, instruments_of_formheader)
        )
        for name in unique_instrument_names:
            instruments_by_name = Instrument.query.filter_by(name=name).all()
            yield instrument_view_object(instruments_by_name)


def instrument_view_object(instruments):
    return {
        "response_type": instruments[0].response_type,
        "code": instruments[0].code,
        "likert_min": instruments[0].likert_min,
        "likert_min_label": instruments[0].likert_min_label,
        "likert_max": instruments[0].likert_max,
        "likert_max_label": instruments[0].likert_max_label,
        "likert_intermediate_labels": list_of_intermediate_labels(
            instruments[0]
        ),
        "questions": questions_from_instruments(instruments),
    }


def questions_from_instruments(instruments):
    questions = list(
        itertools.chain.from_iterable(
            instrument.questions for instrument in instruments
        )
    )

    if instruments[0].randomise:
        random.shuffle(questions)

    return questions


def formheaders_with(tutorial_topic_code):
    return (
        TutorialTopic.query.filter_by(code=tutorial_topic_code)
        .first()
        .form_headers
    )


def list_of_intermediate_labels(instrument):
    if instrument.likert_intermediate_labels:
        return instrument.likert_intermediate_labels.split(", ")
    return None

questionnaire/templates/base.html
{% from "macros/wtforms_helper.html" import form_group %}
<!doctype html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1>

	<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans" />

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <title>UVic ED-D 101 Questionnaires - {% block title %}{% endblock %}</title>

</head>

<body>

  <header>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

      <a class="navbar-brand ml-1" href="{{ request.path }}"><h2>Custom Survey Tool</h2></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <i class="fa fa-bars"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav ml-auto mr-1">

          {% if g.student %}
            <li class="nav-item"><a class="nav-link {% if request.path.endswith("questionnaire-list") %}active{% endif %}" href="{{ url_for("questionnaire.questionnaire_list") }}">List of Surveys</a></li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if request.path.endswith("responses") or request.path.endswith("password-change") or request.path.endswith("export-all-responses")%}active{% endif %}" href="#" id="account_details" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ g.student['username'] }}</a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="account_details">

                {% if g.student.admin %}
                  <a class="dropdown-item" href="{{ url_for("results_display.export_all_responses") }}">Export All Responses</a>
                  <div class="dropdown-divider"></div>
                {% endif %}

                <a class="dropdown-item" href="{{ url_for("results_display.responses") }}">Your Responses</a>
                <a class="dropdown-item" href="{{ url_for("authentication.password_change") }}">Change Password</a>
                <a class="dropdown-item" href="{{ url_for("authentication.logout") }}">Log Out</a>
              </div>
            </li>

          {% else %}

            <li class="nav-item"><a class="nav-link {% if request.path.endswith("login") %} active{% endif %}" href="{{ url_for("authentication.login") }}">Log In</a></li>
            <li class="nav-item"><a class="nav-link {% if request.path.endswith("register") %}active{% endif %}" href="{{ url_for("authentication.register") }}">Register</a></li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if request.path.endswith("get-username") or request.path.endswith("password-reset") %}active{% endif %}" href="#" id="forgot_details" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Forgot Login Details</a>

              <div class="dropdown-menu" aria-labelledby="forgot_details">
                <a class="dropdown-item" href="{{ url_for("authentication.get_username") }}">Forgot Username</a>
                <a class="dropdown-item" href="{{ url_for("authentication.password_reset") }}">Forgot Password</a>
              </div>

            </li>

          {% endif %}
        </ul>
      </div>
    </nav>

  </header>

  <main role="main">
    <div class="container">
      <h2 class="mt-5 mb-4">{% block header %}{% endblock %}</h2>
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="row">
          <div class="alert alert-{{ category }} ml-3" role="alert">
            {{ message }}
          </div>
        </div>
      {% endfor %}

      {% block content %}{% endblock %}
    </div>
  </main>

  <footer id="footer" class="mt-5">
    <div class="p-1">
      <hr />
      <p class="text-center">
        <small class="text-monospace">
          Interested in the code or have a bug to report? Check out the <a class="font-weight-bold" href="https://gitlab.com/dinosawrusrex/uvic-ed-d-questionnaire">code repo</a>! <i class="fa fa-heart"></i>
        </small>
      </p>
      <hr />
    </div>
  </footer>
</body>
</html>

questionnaire/templates/index.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h3 class="text-center">Welcome to the site for UVic ED-D 101 surveys!</h3>
{% endblock %}

questionnaire/templates/questionnaire.html
{% extends "base.html" %}
{% from "macros/questionnaire_header.html" import render_table_header %}
{% from "macros/questionnaire_statements.html" import render_questionnaire_statements %}

{% block header %}{% block title %}{{ title }}{% endblock %}{% endblock %}

{% block content %}


  <form action="{{ url_for('results_display.output') }}" method="POST">
    {% for header in formheaders_and_instruments %}
      <div class="card border-dark mb-3 mt-4">
        <div class="card-body text-dark">
          <div class="card-title"><h4>{{ header.header }}</h4></div>
          <div class="card-text"><p>{{ header.instruction }}</p></div>
        </div>
      </div>

        {% for instrument in formheaders_and_instruments[header] %}
          <table class="table table-borderless table-sm">

            {{ render_table_header(instrument) }}
            {{ render_questionnaire_statements(instrument) }}

          </table>

        {% endfor %}
        <br />
      {% endfor %}
      <input class="btn btn-dark btn-lg" type="submit" value="Submit" />
  </form>
      </div>


{% endblock %}

questionnaire/templates/questionnaire_list.html
{% extends "base.html" %}

{% block title %}Questionnaire List{% endblock %}

{% block header %}<i class="fa fa-list"></i> Surveys{% endblock %}

{% block content %}
  {% for topic in topics %}
    <div class="row">
      <div class="col-4 my-3"><h4>{{ topic.topic }}</h4></div>
      <div class="col my-3">
        <a type="button" class="btn btn-outline-dark" href="{{ url_for("questionnaire.questionnaire", tutorial_topic_code=topic.code)}}"><i class="fa fa-lg fa-arrow-circle-o-right"></i> Complete...</a>
      </div>
    </div>

  {% endfor %}
{% endblock %}

questionnaire/templates/responses.html
{% extends "base.html" %}

{% block title %}Responses{% endblock %}

{% block header %}<i class="fa fa-floppy-o"></i> Your Responses{% endblock %}

{% block content %}
  <ol>
    {% for session in sessions %}
      <li>
        <div class="row">
          <div class="col-3"><p>{{ tutorial(session.tutorial_topic_code) }}</p></div>
          <div class="col">
            <a href="{{ url_for("results_display.response_from_session", session_id=session.id) }}">
              {{ session.timestamp.date() }}
            </a>
          </div>
        </div>
      </li>
    {% endfor %}
  </ol>
{% endblock %}

questionnaire/templates/work_in_progress.html
{% extends "base.html" %}

{% block header %}{% block title %}{{ title }}{% endblock %}{% endblock %}

{% block content %}
Work in progress. Sorry!
{% endblock %}